//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIBActivator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIBActivator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational purposes only. No ads, no music, no bullshit..
        /// </summary>
        internal static string about_hdr_desc {
            get {
                return ResourceManager.GetString("about_hdr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPG KeyID.
        /// </summary>
        internal static string about_lbl_gpg {
            get {
                return ResourceManager.GetString("about_lbl_gpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signature Thumbprint.
        /// </summary>
        internal static string about_lbl_thumbprint {
            get {
                return ResourceManager.GetString("about_lbl_thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patcher Updates.
        /// </summary>
        internal static string about_lnk_github {
            get {
                return ResourceManager.GetString("about_lnk_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        internal static string about_lnk_tpb {
            get {
                return ResourceManager.GetString("about_lnk_tpb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bch {
            get {
                object obj = ResourceManager.GetObject("bch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_header {
            get {
                object obj = ResourceManager.GetObject("bg_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btc {
            get {
                object obj = ResourceManager.GetObject("btc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manually Locate DLL.
        /// </summary>
        internal static string btn_locate {
            get {
                return ResourceManager.GetString("btn_locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Patch.
        /// </summary>
        internal static string btn_patch {
            get {
                return ResourceManager.GetString("btn_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chat {
            get {
                object obj = ResourceManager.GetObject("chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eth {
            get {
                object obj = ResourceManager.GetObject("eth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCH.
        /// </summary>
        internal static string lbl_contrib_bch {
            get {
                return ResourceManager.GetString("lbl_contrib_bch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC.
        /// </summary>
        internal static string lbl_contrib_btc {
            get {
                return ResourceManager.GetString("lbl_contrib_btc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETH.
        /// </summary>
        internal static string lbl_contrib_eth {
            get {
                return ResourceManager.GetString("lbl_contrib_eth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find StartIsBack. It must be installed first before you can run the patcher..
        /// </summary>
        internal static string msgbox_nolocopen_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocopen_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartIsBack Not Found.
        /// </summary>
        internal static string msgbox_nolocopen_title {
            get {
                return ResourceManager.GetString("msgbox_nolocopen_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patcher cannot determine where StartIsBack is installed
        ///Tried looking in {0}
        ///
        ///You will be prompted to manually locate StartIsBackCfg.exe. Ensure that StartIsBack is installed on your system..
        /// </summary>
        internal static string msgbox_nolocpath_msg {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Locate StartIsBack.
        /// </summary>
        internal static string msgbox_nolocpath_title {
            get {
                return ResourceManager.GetString("msgbox_nolocpath_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartIsBack has been successfully patched..
        /// </summary>
        internal static string msgbox_patch_compl_msg {
            get {
                return ResourceManager.GetString("msgbox_patch_compl_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Complete.
        /// </summary>
        internal static string msgbox_patch_compl_title {
            get {
                return ResourceManager.GetString("msgbox_patch_compl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] msimg32 {
            get {
                object obj = ResourceManager.GetObject("msimg32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon sib_128 {
            get {
                object obj = ResourceManager.GetObject("sib_128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sib_logo_1 {
            get {
                object obj = ResourceManager.GetObject("sib_logo_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Patch to begin ....
        /// </summary>
        internal static string statusbar_generate {
            get {
                return ResourceManager.GetString("statusbar_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully patched StartIsBack.
        /// </summary>
        internal static string statusbar_patch_complete {
            get {
                return ResourceManager.GetString("statusbar_patch_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartIsBack not found.
        /// </summary>
        internal static string statusbar_sib_not_found {
            get {
                return ResourceManager.GetString("statusbar_sib_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restart task explorer.exe.
        /// </summary>
        internal static string statusbar_taskkill_cmd {
            get {
                return ResourceManager.GetString("statusbar_taskkill_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not kill task explorer.exe.
        /// </summary>
        internal static string statusbar_taskkill_proc {
            get {
                return ResourceManager.GetString("statusbar_taskkill_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not kill StartIsBackCfg.exe.
        /// </summary>
        internal static string statusbar_taskkill_startallback {
            get {
                return ResourceManager.GetString("statusbar_taskkill_startallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string template_btn_abort {
            get {
                return ResourceManager.GetString("template_btn_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string template_btn_cancel {
            get {
                return ResourceManager.GetString("template_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string template_btn_ignore {
            get {
                return ResourceManager.GetString("template_btn_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string template_btn_no {
            get {
                return ResourceManager.GetString("template_btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string template_btn_ok {
            get {
                return ResourceManager.GetString("template_btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string template_btn_retry {
            get {
                return ResourceManager.GetString("template_btn_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string template_btn_yes {
            get {
                return ResourceManager.GetString("template_btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do this because I enjoy giving back, and I&apos;m not looking to make a profit off my work. However, donations would help immensely for one purpose -- purchasing libraries and other commercial products which have insane licensing systems. These types of products would make life much easier and get releases pumped out on a more regular basis. Don&apos;t feel obligated, this is just &quot;if you can&quot;. My main goal is better tools..
        /// </summary>
        internal static string txt_contrib_intro {
            get {
                return ResourceManager.GetString("txt_contrib_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install StartIsBack before running this patch..
        /// </summary>
        internal static string txt_intro {
            get {
                return ResourceManager.GetString("txt_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program will patch and activate StartIsBack. The process Explorer.exe will restart and make your start menu / taskbar briefly disappear. Be aware that when explorer.exe is restarted; any opened File Explorer windows will be closed..
        /// </summary>
        internal static string txt_intro1 {
            get {
                return ResourceManager.GetString("txt_intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press PATCH to begin..
        /// </summary>
        internal static string txt_intro2 {
            get {
                return ResourceManager.GetString("txt_intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press MANUALLY LOCATE if patch cannot automatically locate StartIsBack..
        /// </summary>
        internal static string txt_intro3 {
            get {
                return ResourceManager.GetString("txt_intro3", resourceCulture);
            }
        }
    }
}
